name: llamaindex-mcp-server
services:
  server:
    image: liteobject/llamaindex-mcp-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - UVICORN_LOG_LEVEL=warning
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
    ports:
      - "8000:8000"
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/rpc"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  mcp-network:
    driver: bridge

volumes:
  logs: